---
title: "Basic 2 - ggplot2"
author: "Vu Thien"
date: "2023-04-06"
output:
  html_document:
    self_contained: true
---
# Import library

```{r}
# ggplot

suppressMessages(library(ggplot2))
suppressMessages(library(ggthemes))
suppressMessages(library(tidyverse))
suppressMessages(library(ggrepel))

```


# How to find file path
```{r}
# a = file.choose()
# a
```

```{r}
crime = read.csv("/Users/thien/Desktop/R-dir/R studying/dataset/Crime dataset reduced.csv")
```




# 1.1 Historgram
```{r}
hist(crime$police)
hist(crime$population)
```




## Step by step
## for variable population

```{r}
# Step 1: With 3 key components (data, mapping, geom_)
ggplot(data = crime, mapping = aes(x = population)) + geom_histogram()

```

```{r}
# Step 2
ggplot(data = crime, mapping = aes(x = population)) + geom_histogram(fill = "blue")
```


```{r}
# Step 3
ggplot(data = crime, mapping = aes(x = population)) + geom_histogram(fill = "blue", col = "white")

```

```{r}
# Step 4
ggplot(data = crime, mapping = aes(x = population)) + 
  geom_histogram(fill = "blue", col = "white", aes(y = ..density..)) +
  geom_density(col = "red")
```

```{r}
# Step 5: Add main title for this graph
ggplot(data = crime, mapping = aes(x = population)) + 
  geom_histogram(fill = "blue", col = "white", aes(y = ..density..)) +
  geom_density(col = "red") +
  ggtitle("Distribution of population")

```

```{r}
# Step 6: Center alignment for the main title
ggplot(data = crime, mapping = aes(x = population)) + 
  geom_histogram(fill = "blue", col = "white", aes(y = ..density..)) +
  geom_density(col = "red") +
  ggtitle("Distribution of population") +
  theme(plot.title = element_text(hjust = 0.5))
```




```{r}
# Step 7: I would like to change to the economist theme
ggplot(data = crime, mapping = aes(x = population)) + 
  geom_histogram(fill = "blue", col = "white", aes(y = ..density..)) +
  geom_density(col = "red") +
  ggtitle("Distribution of population") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_economist() # this theme from library(ggthemes)
```




## for variable police
```{r}
ggplot(crime, aes(police)) + geom_histogram()

ggplot(crime, aes(police)) + geom_histogram(fill = "blue")

ggplot(crime, aes(police)) + geom_histogram(fill = "blue", col = "white")

ggplot(data = crime, aes(x = police)) + 
  geom_histogram(aes(y = ..density..), fill = "blue", col = "white", binwidth = 0.05) +
  geom_density(col = "red")

ggplot(data = crime, aes(x = police)) + 
  geom_histogram(aes(y = ..density..), fill = "blue", col = "white", binwidth = 0.05) +
  geom_density(col = "red") +
  ggtitle("Distribution of the number of police")

ggplot(data = crime, aes(x = police)) + 
  geom_histogram(aes(y = ..density..), fill = "blue", col = "white", binwidth = 0.05) +
  geom_density(col = "red") +
  ggtitle("Distribution of the number of police") +
  theme(plot.title = element_text(hjust = 0.5))

ggplot(data = crime, aes(x = police)) + 
  geom_histogram(aes(y = ..density..), fill = "blue", col = "white", binwidth = 0.05) +
  geom_density(col = "red") +
  ggtitle("Distribution of the number of police") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_bw()



ggplot(data = crime, aes(x = police)) + 
  geom_histogram(aes(y = ..density..), fill = "blue", col = "white", binwidth = 0.05) +
  geom_density(col = "red") +
  ggtitle("Distribution of the number of police") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_economist() # I need the economist theme in the "ggthemes" library
```



# Compare police frequencies between Fresno and Los Angeles

```{r}

two_cities = crime %>% select(city, police, robbery) %>% filter(city %in% c("fresno", "losangel"))

ggplot(two_cities, aes(y = police, col = city)) + geom_boxplot() +
  theme_economist()
```



# Compare robbery frequencies between Fresno and Los Angeles

```{r}
ggplot(two_cities, aes(y = robbery, col = city)) + geom_boxplot() +
  theme_economist()
```



# Examine the relationship between robbery and police 
## For 5 cities

```{r}
ggplot(crime, aes(x = police, y = robbery, col = city)) + geom_point()


ggplot(crime, aes(x = police, y = robbery, col = city)) + geom_point() +
  geom_smooth(method = "lm")

ggplot(crime, aes(x = police, y = robbery, col = city)) + geom_point() +
  geom_smooth(method = "loess")
```



## Only for Los Angeles city

```{r}
los = crime %>% filter(city == "losangel")

ggplot(los, aes(x = police, y = robbery, col = city)) + geom_point() +
  geom_smooth(method = "lm")

ggplot(los, aes(x = police, y = robbery, col = city)) + geom_point() +
  geom_smooth(method = "loess")
```



## Only in 1992 

```{r}
onlyin92 = crime %>% filter(year == 92)

ggplot(onlyin92, aes(x = police, y = robbery, label = city)) + geom_point() +
  geom_smooth(method = "lm", se = F) +
  geom_text_repel(aes(col=city)) + theme_economist()

```

